tap "homebrew/core"
tap "homebrew/cask"
tap "homebrew/services"

# Core CLI
brew "bash"
brew "bat"
brew "bear"
brew "chezmoi"
brew "cmake"
brew "coreutils"
brew "curl"
brew "ctags"
brew "fd"
brew "fio"
brew "fnm"
brew "fzf"
brew "gh"
brew "git"
brew "gnu-sed"
brew "grep"
brew "lsd"
brew "make"
brew "mercurial"
brew "mosh"
brew "openvpn"
brew "qemu"
brew "ripgrep"
brew "rustup"
brew "shellcheck"
brew "shfmt"
brew "stylua"
brew "taplo"
brew "tmux"
brew "tree-sitter"
brew "uv"
brew "vivid"
brew "watchman"
brew "zellij"
brew "zig"
brew "zls"
brew "zoxide"

# Editors / language servers
brew "llvm"
brew "lua-language-server"
brew "neovim"

# macOS apps that match the managed config
cask "alacritty"
cask "karabiner-elements"
cask "orbstack"
