model = "gpt-5.6-sol"
model_reasoning_effort = "xhigh"
personality = "pragmatic"
approval_policy = "never"
approvals_reviewer = "user"
sandbox_mode = "danger-full-access"
service_tier = "fast"
plan_mode_reasoning_effort = "max"


notify = ["/Users/zhdi/.codex/computer-use/Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient", "turn-ended"]

[projects."/Users/zhdi/develop/kbd-platform"]
trust_level = "untrusted"

[projects."/Users/zhdi/develop/kbdv2"]
trust_level = "untrusted"

[projects."/Users/zhdi"]
trust_level = "untrusted"

[projects."/Users/zhdi/develop/kwaistore_scripts"]
trust_level = "trusted"

[projects."/Users/zhdi/develop/kwaistore"]
trust_level = "trusted"

[projects."/Volumes/build-part/linux"]
trust_level = "trusted"

[projects."/Users/zhdi/.config/nvim"]
trust_level = "trusted"

[projects."/Users/zhdi/.config/tmux"]
trust_level = "trusted"

[projects."/Users/zhdi/develop/set-shortcut"]
trust_level = "trusted"

[projects."/Users/zhdi/Downloads/cloudComputeFinal"]
trust_level = "trusted"

[projects."/Users/zhdi/develop/xiaohongshu_collection"]
trust_level = "trusted"

[projects."/Users/zhdi/develop/HYY"]
trust_level = "trusted"

[projects."/Users/zhdi/develop/harmony_news_app_final"]
trust_level = "trusted"

[projects."/Users/zhdi/develop/hyy_paper"]
trust_level = "trusted"

[projects."/Users/zhdi/Documents/Codex/2026-04-26/10-questions-50-points-in-total"]
trust_level = "trusted"

[projects."/Users/zhdi/Documents/Codex/2026-04-26/6-questions-30-points-in-total"]
trust_level = "trusted"

[projects."/Users/zhdi/Documents/Codex/2026-04-26/19-questions-62-7-points-in"]
trust_level = "trusted"

[projects."/Users/zhdi/Documents/Codex/2026-04-26/16-questions-80-points-in-total"]
trust_level = "trusted"

[projects."/Users/zhdi/Documents/Codex/2026-04-26/15-questions-33-points-in-total"]
trust_level = "trusted"

[projects."/Users/zhdi/develop/net_final/protocal"]
trust_level = "trusted"

[projects."/Users/zhdi/develop/net_final/ipv6"]
trust_level = "trusted"

[projects."/Users/zhdi/Documents/Codex/2026-04-27/files-mentioned-by-the-user-1"]
trust_level = "trusted"

[projects."/Users/zhdi/develop/net_final/java"]
trust_level = "trusted"

[projects."/Users/zhdi/develop/net_final/embeded"]
trust_level = "trusted"

[projects."/Users/zhdi/develop/qos_dpu"]
trust_level = "trusted"

[projects."/Users/zhdi/develop/weibo_checkin"]
trust_level = "trusted"

[projects."/Users/zhdi/Downloads/bigdata"]
trust_level = "trusted"

[projects."/Users/zhdi/develop/moive_grab"]
trust_level = "trusted"

[projects."/Users/zhdi/Documents/Codex/2026-05-14/subconverter-https-github-com-tindy2013-subconverter"]
trust_level = "trusted"

[projects."/Users/zhdi/Documents/Codex/2026-05-23/check-out-my-alacritty-config-and"]
trust_level = "trusted"

[projects."/Users/zhdi/develop/alacritty"]
trust_level = "trusted"

[projects."/Users/zhdi/develop/ghostty"]
trust_level = "trusted"

[projects."/Users/zhdi/Documents/Codex/2026-05-27/is-current-my-laptop-has-a"]
trust_level = "trusted"

[projects."/Users/zhdi/Documents/Codex/2026-05-27/how-to-install-andriod-simulator-in"]
trust_level = "trusted"

[projects."/Users/zhdi/Documents/Codex/2026-05-29/codex-desktop-chats-history"]
trust_level = "trusted"

[projects."/Users/zhdi/develop/youtube_crawler"]
trust_level = "trusted"

[projects."/Users/zhdi/develop/ceph"]
trust_level = "trusted"

[projects."/Users/zhdi/develop/alacritty_perf"]
trust_level = "trusted"

[projects."/Users/zhdi/.local/share/nvim/lazy/lualine.nvim"]
trust_level = "trusted"

[projects."/Users/zhdi/master"]
trust_level = "trusted"

[projects."/Users/zhdi/master_apply"]
trust_level = "trusted"

[projects."/Users/zhdi/master_apply/school_choice"]
trust_level = "trusted"

[projects."/Users/zhdi/develop/c_sort_visualization"]
trust_level = "trusted"

[projects."/Users/zhdi/develop/yuketang"]
trust_level = "trusted"

[projects."/Users/zhdi/develop/neovim"]
trust_level = "trusted"

[projects."/Users/zhdi/develop/music_craft"]
trust_level = "trusted"

[projects."/Users/zhdi/Downloads"]
trust_level = "trusted"

[projects."/private/var/folders/zv/v2681z9j6bl20f72psr0df440000gn/T/codex.mPNEkYMPRP"]
trust_level = "trusted"

[projects."/private/var/folders/zv/v2681z9j6bl20f72psr0df440000gn/T/codex.cBffA6Yr6w"]
trust_level = "trusted"

[projects."/private/var/folders/zv/v2681z9j6bl20f72psr0df440000gn/T/codex.IKwbzS6Ne8"]
trust_level = "trusted"

[projects."/private/tmp"]
trust_level = "trusted"

[projects."/private/var/folders/zv/v2681z9j6bl20f72psr0df440000gn/T/codexside.9ODfLvwUZD"]
trust_level = "trusted"

[projects."/private/var/folders/zv/v2681z9j6bl20f72psr0df440000gn/T/codexside.XeM0xhscqn"]
trust_level = "trusted"

[projects."/private/var/folders/zv/v2681z9j6bl20f72psr0df440000gn/T/codexside.Bny26Xrca5"]
trust_level = "trusted"

[projects."/private/var/folders/zv/v2681z9j6bl20f72psr0df440000gn/T/codexside.7TI9e8wfVr"]
trust_level = "trusted"

[projects."/private/var/folders/zv/v2681z9j6bl20f72psr0df440000gn/T/codexside.MSYxrwCLya"]
trust_level = "trusted"

[projects."/private/var/folders/zv/v2681z9j6bl20f72psr0df440000gn/T/codexside.jsMMNVKVLi"]
trust_level = "trusted"

[projects."/private/var/folders/zv/v2681z9j6bl20f72psr0df440000gn/T/codexside.8togU9394F"]
trust_level = "trusted"

[projects."/Users/zhdi/develop/gfw"]
trust_level = "trusted"

[projects."/private/var/folders/zv/v2681z9j6bl20f72psr0df440000gn/T/codexside.3arKl6vxxs"]
trust_level = "trusted"

[projects."/private/var/folders/zv/v2681z9j6bl20f72psr0df440000gn/T/codexside.BumQFevhB6"]
trust_level = "trusted"

[projects."/mnt/mac/Volumes/build_part/ceph-toolbox"]
trust_level = "trusted"

[projects."/mnt/mac/Volumes/build_part/ceph"]
trust_level = "trusted"

[projects."/mnt/mac/Volumes/build_part/ceph-client-work/5.14"]
trust_level = "trusted"

[projects."/home/zhdi"]
trust_level = "trusted"

[projects."/mnt/mac/Volumes/build_part/rh_linux"]
trust_level = "trusted"

[projects."/mnt/mac/Volumes/build_part/ceph-client-work"]
trust_level = "trusted"

[projects."/home/zhdi/.config/nvim"]
trust_level = "trusted"

[projects."/mnt/mac/Volumes/build_part/kbuilder"]
trust_level = "trusted"

[projects."/mnt/mac/Volumes/build_part/storage_advise"]
trust_level = "trusted"

[projects."/mnt/mac/Volumes/build_part/snake"]
trust_level = "trusted"

[projects."/mnt/mac/Volumes/build_part/kfs-agent"]
trust_level = "trusted"

[projects."/mnt/mac/Volumes/build_part/kfs-platform"]
trust_level = "trusted"

[projects."/mnt/mac/Volumes/build_part/bootstrap-host"]
trust_level = "trusted"

[projects."/mnt/mac/Volumes/build_part/history_exporter"]
trust_level = "trusted"

[notice]
hide_rate_limit_model_nudge = true

[notice.model_migrations]
"gpt-5.2" = "gpt-5.2-codex"

[features]
multi_agent = true
# js_repl = false

[mcp_servers.playwright]
args = ["@playwright/mcp@latest"]
command = "npx"

[marketplaces.openai-bundled]
last_updated = "2026-06-18T16:44:22Z"
source_type = "local"
source = "/Users/zhdi/.codex/.tmp/bundled-marketplaces/openai-bundled"

[marketplaces.openai-primary-runtime]
last_updated = "2026-06-01T18:12:28Z"
source_type = "local"
source = "/Users/zhdi/.cache/codex-runtimes/codex-primary-runtime/plugins/openai-primary-runtime"

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[plugins."chrome@openai-bundled"]
enabled = false

[plugins."browser@openai-bundled"]
enabled = false

[desktop]
appearanceTheme = "system"
appearanceLightCodeThemeId = "gruvbox"
appearanceDarkCodeThemeId = "gruvbox"
composerEnterBehavior = "cmdIfMultiline"
preventSleepWhileRunning = true
keepRemoteControlAwakeWhilePluggedIn = true
notifications-permissions-enabled = true
default-service-tier = "priority"
followUpQueueMode = "steer"
show-context-window-usage = true

[desktop.appearanceLightChromeTheme]
accent = "#458588"
contrast = 45
ink = "#3c3836"
opaqueWindows = false
surface = "#fbf1c7"

[desktop.appearanceLightChromeTheme.fonts]

[desktop.appearanceLightChromeTheme.semanticColors]
diffAdded = "#3c3836"
diffRemoved = "#cc241d"
skill = "#b16286"

[desktop.appearanceDarkChromeTheme]
accent = "#458588"
contrast = 60
ink = "#ebdbb2"
opaqueWindows = false
surface = "#282828"

[desktop.appearanceDarkChromeTheme.fonts]

[desktop.appearanceDarkChromeTheme.semanticColors]
diffAdded = "#ebdbb2"
diffRemoved = "#cc241d"
skill = "#b16286"

[desktop.open-in-target-preferences]
global = "zed"

[desktop.open-in-target-preferences.perPath]
"/Users/zhdi/.config/nvim" = "ghostty"
"/Users/zhdi/develop/codex" = "zed"
"/Volumes/build-part/linux" = "zed"

[tui]
status_line = ["model-with-reasoning", "current-dir", "project-name", "git-branch", "branch-changes", "run-state", "context-used", "five-hour-limit", "weekly-limit", "task-progress"]
status_line_use_colors = true
theme = "gruvbox-light"

[tui.model_availability_nux]
"gpt-5.5" = 4
"gpt-5.6-sol" = 4
