unbind-key C-b

set-option -g prefix S-F12

bind-key S-F12 send-prefix
setw -g mode-keys vi

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection
bind-key -T copy-mode-vi Y send-keys -X copy-line
bind-key -T copy-mode-vi a send-keys -X append-selection
bind-key -T prefix l select-pane -R
bind-key -T prefix h select-pane -L
bind-key -T prefix j select-pane -D
bind-key -T prefix k select-pane -U
bind-key -r -T prefix C-k resize-pane -U
bind-key -r -T prefix C-j resize-pane -D
bind-key -r -T prefix C-l resize-pane -R
bind-key -r -T prefix C-h resize-pane -L
bind-key -r -T prefix M-k resize-pane -U 5
bind-key -r -T prefix M-j resize-pane -D 5
bind-key -r -T prefix M-l resize-pane -R 5
bind-key -r -T prefix M-h resize-pane -L 5
bind-key -T prefix o last-window

# bind-key -T nvim-nav h select-pane -L
# bind-key -T nvim-nav j select-pane -D
# bind-key -T nvim-nav k select-pane -U
# bind-key -T nvim-nav l select-pane -R
#
# bind-key -n C-w if-shell "tmux list-panes -F '#{pane_current_command}' | rg 'nvim'" "switch-client -T nvim-nav"
# bind-key -T nvim-nav any switch-client -T root
set -g monitor-bell on
set -g bell-action any
# set-hook -g alert-bell 'run-shell "afplay /System/Library/Sounds/Funk.aiff"'
set -g default-shell /bin/zsh
set -g default-command "/bin/zsh -l"

set -s set-clipboard on
set-option -g xterm-keys on
set -sg escape-time 0
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-strategy-nvim 'session'
set -g @continuum-restore 'on'
set -g @tmux-remote-sessions-vim-navigation on
set -g @tmux-remote-sessions-preserve-current-path on


set-environment -g PATH "/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"


set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'git@github.com:ZHDI-1/tmux-remote-sessions.git'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

if-shell 'test -d "$HOME/.config/tmux/plugins/tpm"' \
  'run-shell "$HOME/.config/tmux/plugins/tpm/tpm > $HOME/.config/tmux/log"' \
  'run-shell "git clone https://github.com/tmux-plugins/tpm \"$HOME/.config/tmux/plugins/tpm\" && \"$HOME/.config/tmux/plugins/tpm/tpm\""'
